title: SwissCHI Pathways
description: SwissCHI Student Chapter - Pathways
baseurl: ""
url: "https://swisschi-pathways.org"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - CLAUDE.md